name: namer_app
description: A new Flutter project.

publish_to: 'none' 

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  youtube_player_flutter: ^8.0.0
  visibility_detector: ^0.4.0+2
  google_nav_bar: ^5.0.6
  english_words: ^4.0.0
  video_player: ^2.7.2
  gap: ^3.0.1
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  shared_preferences: ^2.2.2
  path_provider_linux: ^2.2.1
  path_provider_windows: ^2.2.1
  confetti: ^0.7.0
  bloc: ^8.1.2
  equatable: ^2.0.5
  meta: ^1.9.0
  flutter_bloc: ^8.1.3
  provider: ^6.1.1
  stacked_themes: ^0.3.12
  theme_provider: ^0.6.0
  flutter_tts: ^3.8.5
  path: ^1.8.3
  stacked: ^3.4.1+1
  path_provider: ^2.1.1
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  # flutter_bloc: ^8.1.3
  # equatable: ^2.0.5

flutter:
  uses-material-design: true
  assets:
  - lib/assets/texts/
  - lib/assets/images/
  - lib/assets/images/login/

  fonts:
  - family: ShareTechMono
    fonts:
      - asset: lib/assets/fonts/ShareTechMono-Regular.ttf
  - family: RobotoMono
    fonts:
      - asset: lib/assets/fonts/RobotoMono-Regular.ttf
      - asset: lib/assets/fonts/RobotoMono-Bold.ttf
        weight: 700
